# Generated by Django 2.0 on 2017-12-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='name',
            new_name='lead_name',
        ),
    ]
