# Generated by Django 2.0 on 2017-12-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20171219_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
