# Generated by Django 2.0 on 2017-12-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_tours_json_ld'),
        ('leads', '0003_join_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='url_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Tours'),
        ),
    ]
