# Generated by Django 2.0 on 2017-12-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_join_url_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='url_field',
        ),
    ]
