# Generated by Django 2.0 on 2018-01-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_tours_leave_capture'),
        ('leads', '0006_join_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Tours'),
        ),
    ]
