# Generated by Django 2.0 on 2017-12-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_keywords', models.TextField(blank=True, null=True)),
                ('head_description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_title', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('video_embed', models.TextField(blank=True, null=True)),
                ('dates', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tour_program', models.TextField(blank=True, null=True)),
                ('included', models.TextField(blank=True, null=True)),
                ('not_included', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='page-slug', unique=True)),
                ('draft', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('bus', 'Bus'), ('avia', 'Avia'), ('individual', 'Individual'), ('corporate', 'Corporate')], default='bus', max_length=20)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
