# Generated by Django 2.0 on 2017-12-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171211_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='name',
            new_name='tour_name',
        ),
    ]
