# Generated by Django 2.0 on 2017-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20171224_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='json_ld',
            field=models.TextField(blank=True, null=True),
        ),
    ]
