# Generated by Django 2.0 on 2017-12-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_tours_json_ld'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='leave_capture',
            field=models.BooleanField(default=True),
        ),
    ]
